// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRw85r9adbcmsCm17CUuPyFlxtxlouveU',
    appId: '1:248476231134:web:c9f49e0227c5372cfbe94f',
    messagingSenderId: '248476231134',
    projectId: 'deteksi-kebakaran-iot',
    authDomain: 'deteksi-kebakaran-iot.firebaseapp.com',
    databaseURL: 'https://deteksi-kebakaran-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deteksi-kebakaran-iot.firebasestorage.app',
    measurementId: 'G-4J39HJWD6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDyX1uW3OBlGYDy5dc25U7Oma3edQZFOU',
    appId: '1:248476231134:android:7102f77310f5c2d7fbe94f',
    messagingSenderId: '248476231134',
    projectId: 'deteksi-kebakaran-iot',
    databaseURL: 'https://deteksi-kebakaran-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deteksi-kebakaran-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMx0VORNtU0Doz2UwY2XZMfUpdXluqN5s',
    appId: '1:248476231134:ios:8cbee46ce38a998cfbe94f',
    messagingSenderId: '248476231134',
    projectId: 'deteksi-kebakaran-iot',
    databaseURL: 'https://deteksi-kebakaran-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deteksi-kebakaran-iot.firebasestorage.app',
    iosBundleId: 'com.example.fireDetectionIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMx0VORNtU0Doz2UwY2XZMfUpdXluqN5s',
    appId: '1:248476231134:ios:8cbee46ce38a998cfbe94f',
    messagingSenderId: '248476231134',
    projectId: 'deteksi-kebakaran-iot',
    databaseURL: 'https://deteksi-kebakaran-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deteksi-kebakaran-iot.firebasestorage.app',
    iosBundleId: 'com.example.fireDetectionIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRw85r9adbcmsCm17CUuPyFlxtxlouveU',
    appId: '1:248476231134:web:15c383eb69f33c49fbe94f',
    messagingSenderId: '248476231134',
    projectId: 'deteksi-kebakaran-iot',
    authDomain: 'deteksi-kebakaran-iot.firebaseapp.com',
    databaseURL: 'https://deteksi-kebakaran-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deteksi-kebakaran-iot.firebasestorage.app',
    measurementId: 'G-888QZFEBPZ',
  );

}